"""empty message

Revision ID: e9863d840718
Revises: 
Create Date: 2023-06-27 12:11:26.336583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9863d840718'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('eid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ename', sa.String(length=512), nullable=False),
    sa.Column('edesc', sa.String(length=512), nullable=False),
    sa.Column('edate', sa.String(length=512), nullable=False),
    sa.Column('eposter', sa.String(length=512), nullable=False),
    sa.Column('evenue', sa.String(length=512), nullable=False),
    sa.Column('edept', sa.String(length=512), nullable=False),
    sa.Column('oname', sa.String(length=512), nullable=False),
    sa.Column('odept', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('eid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
